acme_my:
    resource: "@AcmeMyBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
    
homepage:
    path:     /
    defaults: { _controller: AcmeMyBundle:Home:index }
