ajax:
    path:     /ajax/
    defaults: { _controller: AcmeMyBundle:Ajax:index }
album:
    path:     /album/{type}
    defaults: { _controller: AcmeMyBundle:Album:index }
builder:
    path:     /builder/{name}
    defaults: { _controller: AcmeMyBundle:Builder:index }
community:
    path:     /community/{id}
    defaults: { _controller: AcmeMyBundle:Community:index }
home:
    path:     /home/{area}/{page}
    defaults: { _controller: AcmeMyBundle:Home:index }
h:
    path:     /h/{id}
    defaults: { _controller: AcmeMyBundle:Home:home_detail }
homepage:
    path:     /location/
    defaults: { _controller: AcmeMyBundle:Home:index }
mail:
    path:     /mail/
    defaults: { _controller: AcmeMyBundle:Mail:index }
manage:
    path:     /manage/{type}
    defaults: { _controller: AcmeMyBundle:Manage:index }
model:
    path:     /model/{id}
    defaults: { _controller: AcmeMyBundle:Model:index }
search:
    path:     /search/
    defaults: { _controller: AcmeMyBundle:Home:home_search }
