album:
    path:     /album/{type}
    defaults: { _controller: AcmeMyBundle:Album:index }
builder:
    path:     /builder/{name}
    defaults: { _controller: AcmeMyBundle:Builder:index }
community:
    path:     /community/{id}
    defaults: { _controller: AcmeMyBundle:Community:index }
home:
    path:     /home/{area}/{page}
    defaults: { _controller: AcmeMyBundle:Home:index }
homepage:
    path:     /location/
    defaults: { _controller: AcmeMyBundle:Home:index }
la:
    path:     /la/
    defaults: { _controller: AcmeMyBundle:LA:index }
manage:
    path:     /manage/{type}
    defaults: { _controller: AcmeMyBundle:Manage:index }
model:
    path:     /model/{id}
    defaults: { _controller: AcmeMyBundle:Model:index }
portland:
    path:     /portland/
    defaults: { _controller: AcmeMyBundle:Portland:index }
seattle:
    path:     /seattle/
    defaults: { _controller: AcmeMyBundle:Seattle:index }
sf:
    path:     /sf/
    defaults: { _controller: AcmeMyBundle:SF:index }
